# -*- coding: utf-8 -*-

# MainWindow implementation generated from reading ui file 'HW2_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
import cv2
import imutils


class HW2(QtWidgets.QDialog):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 1025)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlLayout = QtWidgets.QGridLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.brightness = QtWidgets.QLabel(MainWindow)
        self.brightness.setObjectName("brightness")
        self.controlLayout.addWidget(self.brightness, 3, 2, 1, 1)
        self.load = QtWidgets.QPushButton(MainWindow)
        self.load.setObjectName("load")
        self.controlLayout.addWidget(self.load, 0, 0, 1, 1)
        self.threshold = QtWidgets.QLabel(MainWindow)
        self.threshold.setObjectName("threshold")
        self.controlLayout.addWidget(self.threshold, 1, 0, 1, 1)
        self.brightnessNum = QtWidgets.QSlider(MainWindow)
        self.brightnessNum.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessNum.setObjectName("brightnessNum")
        self.controlLayout.addWidget(self.brightnessNum, 3, 3, 1, 1)
        self.grayScaleLevelsNum = QtWidgets.QLineEdit(MainWindow)
        self.grayScaleLevelsNum.setObjectName("grayScaleLevelsNum")
        self.controlLayout.addWidget(self.grayScaleLevelsNum, 4, 1, 1, 1)
        self.contrastNum = QtWidgets.QSlider(MainWindow)
        self.contrastNum.setOrientation(QtCore.Qt.Horizontal)
        self.contrastNum.setObjectName("contrastNum")
        self.controlLayout.addWidget(self.contrastNum, 4, 3, 1, 1)
        self.spatialResolution = QtWidgets.QLabel(MainWindow)
        self.spatialResolution.setObjectName("spatialResolution")
        self.controlLayout.addWidget(self.spatialResolution, 3, 0, 1, 1)
        self.thresholdNum = QtWidgets.QLineEdit(MainWindow)
        self.thresholdNum.setObjectName("thresholdNum")
        self.controlLayout.addWidget(self.thresholdNum, 1, 1, 1, 1)
        self.spatialResolutionNum = QtWidgets.QLineEdit(MainWindow)
        self.spatialResolutionNum.setObjectName("spatialResolutionNum")
        self.controlLayout.addWidget(self.spatialResolutionNum, 3, 1, 1, 1)
        self.autoConstrastAjustment = QtWidgets.QCheckBox(MainWindow)
        self.autoConstrastAjustment.setObjectName("autoConstrastAjustment")
        self.controlLayout.addWidget(self.autoConstrastAjustment, 0, 1, 1, 3)
        self.contrast = QtWidgets.QLabel(MainWindow)
        self.contrast.setObjectName("contrast")
        self.controlLayout.addWidget(self.contrast, 4, 2, 1, 1)
        self.grayscaleLevels = QtWidgets.QLabel(MainWindow)
        self.grayscaleLevels.setObjectName("grayscaleLevels")
        self.controlLayout.addWidget(self.grayscaleLevels, 4, 0, 1, 1)
        self.confirm = QtWidgets.QPushButton(MainWindow)
        self.confirm.setObjectName("confirm")
        self.controlLayout.addWidget(self.confirm, 5, 3, 1, 1)
        self.verticalLayout.addLayout(self.controlLayout)
        self.imageLayout = QtWidgets.QGridLayout()
        self.imageLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.imageLayout.setObjectName("imageLayout")
        self.histogramA = QtWidgets.QLabel(MainWindow)
        self.histogramA.setMinimumSize(QtCore.QSize(200, 200))
        self.histogramA.setText("")
        self.histogramA.setObjectName("histogramA")
        self.imageLayout.addWidget(self.histogramA, 1, 1, 1, 1)
        self.histogramB = QtWidgets.QLabel(MainWindow)
        self.histogramB.setMinimumSize(QtCore.QSize(200, 200))
        self.histogramB.setText("")
        self.histogramB.setObjectName("histogramB")
        self.imageLayout.addWidget(self.histogramB, 2, 1, 1, 1)
        self.grayImageA = QtWidgets.QLabel(MainWindow)
        self.grayImageA.setMinimumSize(QtCore.QSize(200, 200))
        self.grayImageA.setText("")
        self.grayImageA.setObjectName("grayImageA")
        self.imageLayout.addWidget(self.grayImageA, 1, 0, 1, 1)
        self.grayImageB = QtWidgets.QLabel(MainWindow)
        self.grayImageB.setMinimumSize(QtCore.QSize(200, 200))
        self.grayImageB.setText("")
        self.grayImageB.setObjectName("grayImageB")
        self.imageLayout.addWidget(self.grayImageB, 2, 0, 1, 1)
        self.orginalImage = QtWidgets.QLabel(MainWindow)
        self.orginalImage.setMinimumSize(QtCore.QSize(200, 200))
        self.orginalImage.setText("")
        self.orginalImage.setObjectName("orginalImage")
        self.imageLayout.addWidget(self.orginalImage, 0, 0, 1, 1)
        self.compareImage = QtWidgets.QLabel(MainWindow)
        self.compareImage.setText("")
        self.compareImage.setObjectName("compareImage")
        self.imageLayout.addWidget(self.compareImage, 1, 2, 2, 1)
        self.verticalLayout.addLayout(self.imageLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.brightness.setText(_translate("MainWindow", "Brightness"))
        self.load.setText(_translate("MainWindow", "choose input image"))
        self.threshold.setText(_translate("MainWindow", "Threshod to a Binary Image"))
        self.spatialResolution.setText(_translate("MainWindow", "Spatial Resolution"))
        self.autoConstrastAjustment.setText(_translate("MainWindow", "Automatic Constrast Adjustment"))
        self.contrast.setText(_translate("MainWindow", "Constrast"))
        self.grayscaleLevels.setText(_translate("MainWindow", "Grayscale Levels"))
        self.confirm.setText(_translate("MainWindow", "Confirm"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = HW2()
    ui.show()
    sys.exit(app.exec_())
