# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW5_layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(796, 1109)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlLayout = QtWidgets.QGridLayout()
        self.controlLayout.setHorizontalSpacing(6)
        self.controlLayout.setObjectName("controlLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.controlLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.showNumber = QtWidgets.QSpinBox(Form)
        self.showNumber.setMaximum(21)
        self.showNumber.setObjectName("showNumber")
        self.controlLayout.addWidget(self.showNumber, 1, 7, 1, 1)
        self.p3Confirm = QtWidgets.QPushButton(Form)
        self.p3Confirm.setMinimumSize(QtCore.QSize(75, 0))
        self.p3Confirm.setObjectName("p3Confirm")
        self.controlLayout.addWidget(self.p3Confirm, 2, 7, 1, 1)
        self.p3Epsilon = QtWidgets.QLineEdit(Form)
        self.p3Epsilon.setMinimumSize(QtCore.QSize(50, 0))
        self.p3Epsilon.setObjectName("p3Epsilon")
        self.controlLayout.addWidget(self.p3Epsilon, 2, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setMinimumSize(QtCore.QSize(75, 0))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.controlLayout.addWidget(self.label_13, 2, 5, 1, 1)
        self.p3K = QtWidgets.QLineEdit(Form)
        self.p3K.setMinimumSize(QtCore.QSize(50, 0))
        self.p3K.setObjectName("p3K")
        self.controlLayout.addWidget(self.p3K, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.controlLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.controlLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setMinimumSize(QtCore.QSize(75, 0))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.controlLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.p3Max = QtWidgets.QLineEdit(Form)
        self.p3Max.setMinimumSize(QtCore.QSize(50, 0))
        self.p3Max.setObjectName("p3Max")
        self.controlLayout.addWidget(self.p3Max, 2, 4, 1, 1)
        self.p1Confirm = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1Confirm.sizePolicy().hasHeightForWidth())
        self.p1Confirm.setSizePolicy(sizePolicy)
        self.p1Confirm.setMinimumSize(QtCore.QSize(100, 0))
        self.p1Confirm.setObjectName("p1Confirm")
        self.controlLayout.addWidget(self.p1Confirm, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.controlLayout.addWidget(self.label_14, 1, 0, 1, 3)
        self.load = QtWidgets.QPushButton(Form)
        self.load.setMinimumSize(QtCore.QSize(100, 0))
        self.load.setObjectName("load")
        self.controlLayout.addWidget(self.load, 0, 0, 1, 2)
        self.mapNumber = QtWidgets.QSlider(Form)
        self.mapNumber.setMaximum(21)
        self.mapNumber.setOrientation(QtCore.Qt.Horizontal)
        self.mapNumber.setObjectName("mapNumber")
        self.controlLayout.addWidget(self.mapNumber, 1, 5, 1, 2)
        self.mapType = QtWidgets.QLabel(Form)
        self.mapType.setText("")
        self.mapType.setAlignment(QtCore.Qt.AlignCenter)
        self.mapType.setObjectName("mapType")
        self.controlLayout.addWidget(self.mapType, 0, 5, 1, 3)
        self.clean = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clean.sizePolicy().hasHeightForWidth())
        self.clean.setSizePolicy(sizePolicy)
        self.clean.setMinimumSize(QtCore.QSize(100, 0))
        self.clean.setObjectName("clean")
        self.controlLayout.addWidget(self.clean, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.controlLayout)
        self.imageLayout = QtWidgets.QGridLayout()
        self.imageLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.imageLayout.setObjectName("imageLayout")
        self.modifiedImage2 = QtWidgets.QLabel(Form)
        self.modifiedImage2.setMinimumSize(QtCore.QSize(380, 285))
        self.modifiedImage2.setText("")
        self.modifiedImage2.setObjectName("modifiedImage2")
        self.imageLayout.addWidget(self.modifiedImage2, 1, 0, 1, 1)
        self.modifiedImage4 = QtWidgets.QLabel(Form)
        self.modifiedImage4.setMinimumSize(QtCore.QSize(380, 285))
        self.modifiedImage4.setText("")
        self.modifiedImage4.setObjectName("modifiedImage4")
        self.imageLayout.addWidget(self.modifiedImage4, 2, 0, 1, 1)
        self.modifiedImage5 = QtWidgets.QLabel(Form)
        self.modifiedImage5.setMinimumSize(QtCore.QSize(380, 285))
        self.modifiedImage5.setText("")
        self.modifiedImage5.setObjectName("modifiedImage5")
        self.imageLayout.addWidget(self.modifiedImage5, 2, 1, 1, 1)
        self.modifiedImage3 = QtWidgets.QLabel(Form)
        self.modifiedImage3.setMinimumSize(QtCore.QSize(380, 285))
        self.modifiedImage3.setText("")
        self.modifiedImage3.setObjectName("modifiedImage3")
        self.imageLayout.addWidget(self.modifiedImage3, 1, 1, 1, 1)
        self.modifiedImage1 = QtWidgets.QLabel(Form)
        self.modifiedImage1.setMinimumSize(QtCore.QSize(380, 380))
        self.modifiedImage1.setText("")
        self.modifiedImage1.setObjectName("modifiedImage1")
        self.imageLayout.addWidget(self.modifiedImage1, 0, 1, 1, 1)
        self.originalImage = QtWidgets.QLabel(Form)
        self.originalImage.setMinimumSize(QtCore.QSize(380, 380))
        self.originalImage.setText("")
        self.originalImage.setObjectName("originalImage")
        self.imageLayout.addWidget(self.originalImage, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.imageLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Part 2:"))
        self.p3Confirm.setText(_translate("Form", "P3Confirm"))
        self.label_13.setText(_translate("Form", "epsilon:"))
        self.label_2.setText(_translate("Form", "Part 3:"))
        self.label_9.setText(_translate("Form", "k:"))
        self.label_10.setText(_translate("Form", "max_iter:"))
        self.p1Confirm.setText(_translate("Form", "P1Confirm"))
        self.label_14.setText(_translate("Form", "Part1:"))
        self.load.setText(_translate("Form", "Load"))
        self.clean.setText(_translate("Form", "Clean"))

