# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW3/HW3_layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 800)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlLayout = QtWidgets.QGridLayout()
        self.controlLayout.setHorizontalSpacing(6)
        self.controlLayout.setObjectName("controlLayout")
        self.load = QtWidgets.QPushButton(Form)
        self.load.setObjectName("load")
        self.controlLayout.addWidget(self.load, 0, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.controlLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.controlLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.p2Row = QtWidgets.QLineEdit(Form)
        self.p2Row.setObjectName("p2Row")
        self.controlLayout.addWidget(self.p2Row, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.controlLayout.addWidget(self.label, 1, 3, 1, 1)
        self.p2Column = QtWidgets.QLineEdit(Form)
        self.p2Column.setObjectName("p2Column")
        self.controlLayout.addWidget(self.p2Column, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.controlLayout.addWidget(self.label_5, 1, 5, 1, 1)
        self.p2Coefficients = QtWidgets.QLineEdit(Form)
        self.p2Coefficients.setObjectName("p2Coefficients")
        self.controlLayout.addWidget(self.p2Coefficients, 1, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.controlLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setObjectName("label_4")
        self.controlLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setObjectName("label_6")
        self.controlLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setObjectName("label_13")
        self.controlLayout.addWidget(self.label_13, 4, 5, 1, 1)
        self.constantK1 = QtWidgets.QLineEdit(Form)
        self.constantK1.setObjectName("constantK1")
        self.controlLayout.addWidget(self.constantK1, 3, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.controlLayout.addWidget(self.label_7, 3, 3, 1, 1)
        self.p3Confirm = QtWidgets.QPushButton(Form)
        self.p3Confirm.setObjectName("p3Confirm")
        self.controlLayout.addWidget(self.p3Confirm, 2, 7, 1, 1)
        self.p2Confirm = QtWidgets.QPushButton(Form)
        self.p2Confirm.setObjectName("p2Confirm")
        self.controlLayout.addWidget(self.p2Confirm, 1, 7, 1, 1)
        self.p3LoG = QtWidgets.QCheckBox(Form)
        self.p3LoG.setObjectName("p3LoG")
        self.controlLayout.addWidget(self.p3LoG, 2, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.controlLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.p3Threshold = QtWidgets.QLineEdit(Form)
        self.p3Threshold.setObjectName("p3Threshold")
        self.controlLayout.addWidget(self.p3Threshold, 2, 2, 1, 1)
        self.constantK2_2 = QtWidgets.QLineEdit(Form)
        self.constantK2_2.setObjectName("constantK2_2")
        self.controlLayout.addWidget(self.constantK2_2, 3, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.controlLayout.addWidget(self.label_10, 3, 5, 1, 1)
        self.p4Confirm = QtWidgets.QPushButton(Form)
        self.p4Confirm.setObjectName("p4Confirm")
        self.controlLayout.addWidget(self.p4Confirm, 3, 7, 1, 1)
        self.constantK2 = QtWidgets.QLineEdit(Form)
        self.constantK2.setObjectName("constantK2")
        self.controlLayout.addWidget(self.constantK2, 4, 2, 1, 1)
        self.constantC = QtWidgets.QLineEdit(Form)
        self.constantC.setObjectName("constantC")
        self.controlLayout.addWidget(self.constantC, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setObjectName("label_11")
        self.controlLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.constantK3 = QtWidgets.QLineEdit(Form)
        self.constantK3.setObjectName("constantK3")
        self.controlLayout.addWidget(self.constantK3, 4, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setObjectName("label_12")
        self.controlLayout.addWidget(self.label_12, 4, 3, 1, 1)
        self.regionSize = QtWidgets.QLineEdit(Form)
        self.regionSize.setObjectName("regionSize")
        self.controlLayout.addWidget(self.regionSize, 4, 6, 1, 1)
        self.verticalLayout.addLayout(self.controlLayout)
        self.imageLayout = QtWidgets.QGridLayout()
        self.imageLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.imageLayout.setObjectName("imageLayout")
        self.modifiedImageA = QtWidgets.QLabel(Form)
        self.modifiedImageA.setMinimumSize(QtCore.QSize(300, 300))
        self.modifiedImageA.setText("")
        self.modifiedImageA.setObjectName("modifiedImageA")
        self.imageLayout.addWidget(self.modifiedImageA, 1, 0, 1, 1)
        self.originalImage = QtWidgets.QLabel(Form)
        self.originalImage.setMinimumSize(QtCore.QSize(300, 300))
        self.originalImage.setText("")
        self.originalImage.setObjectName("originalImage")
        self.imageLayout.addWidget(self.originalImage, 0, 0, 1, 1)
        self.modifiedImageB = QtWidgets.QLabel(Form)
        self.modifiedImageB.setMinimumSize(QtCore.QSize(300, 300))
        self.modifiedImageB.setText("")
        self.modifiedImageB.setObjectName("modifiedImageB")
        self.imageLayout.addWidget(self.modifiedImageB, 1, 1, 1, 1)
        self.modifiedImageC = QtWidgets.QLabel(Form)
        self.modifiedImageC.setMinimumSize(QtCore.QSize(300, 300))
        self.modifiedImageC.setText("")
        self.modifiedImageC.setObjectName("modifiedImageC")
        self.imageLayout.addWidget(self.modifiedImageC, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.imageLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load.setText(_translate("Form", "Load"))
        self.label_3.setText(_translate("Form", "Part 2"))
        self.label_8.setText(_translate("Form", "row: "))
        self.label.setText(_translate("Form", "column:"))
        self.label_5.setText(_translate("Form", "Coefficients:"))
        self.label_2.setText(_translate("Form", "Part 3"))
        self.label_4.setText(_translate("Form", "Part 4"))
        self.label_6.setText(_translate("Form", "C:"))
        self.label_13.setText(_translate("Form", "region:"))
        self.label_7.setText(_translate("Form", "k0:"))
        self.p3Confirm.setText(_translate("Form", "Confirm"))
        self.p2Confirm.setText(_translate("Form", "Confirm"))
        self.p3LoG.setText(_translate("Form", "Laplacian of Gaussian"))
        self.label_9.setText(_translate("Form", "Threshold: "))
        self.label_10.setText(_translate("Form", "k1:"))
        self.p4Confirm.setText(_translate("Form", "Confirm"))
        self.label_11.setText(_translate("Form", "k2:"))
        self.label_12.setText(_translate("Form", "k3:"))
